/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proshivam;

/**
 *
 * @author INFO12
 */
public class help extends javax.swing.JFrame {

    /**
     * Creates new form help
     */
    public help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Helpdesk");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 153, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("                                     Kaun banega Crorepati\n\n--> HOW TO PLAY\n\n1. If you are a new user..fill your details in new user menu....\n\n2. Carefully type your Mobile no. as it will allow you to play the game again with your Registerd Mobile no.\n\n3. In the game, there are 15 Questions -Starting from Rs.5000 to 7 Crore.\n\n4. There are 5 stages-(i)10,000  (ii)3,20,000   (iii) 1 Crore (iv) 5 Crore  (v) 7 crore\n\n5. After you cross each Stage ...A cheque of Appreciation will be awarded to u...\n\n6. If you give an incorrect answer , then you will get the amount of last stage won...\n\n7. In the game You can quit at any moment, which allows you to win the amount of last question answered Correctly...\n\n8. In the game...if u have any difficulty in answering any Question\n   there are 4 lifelines for your help--\n   (a) Audience Poll--> Take the help of virtual audience..\n   (b) Expert Advice -->  Take the help of virtual expert..\n   (c) Double dip --> You will be allowed to answer twice...but...it has constraint .. You can neither Merge 50:50 with it nor Quit for that particular Question\n   (d) 50:50 --> Two of the incorrect answers will be eliminated ...but...it has constraint .. You can neither Merge double dip with it nor Quit for that particular Question.\n\n9. All the Best....\n\n--> Features of Game\n\n1. High score table:--> you can see it in the About Menu.. It will display the Top 10 high scores ever made in the game...\n\n2. Utility menu --> You can open  (i) calculator (ii) paint  (iii) window media player  (iv) notepad \n                    by this software.......\n\n3. Questionaire menu --> Admins only have the right for this menu i.e. to insert new Question ,update a Question,  and delete a Question\n   for this You have to login in admin menu........");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
