package proshivam;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */ import java.sql.*;

import javax.swing.*;

public class quiz extends javax.swing.JFrame {
 public Connection con=null;
 public Statement stmt=null;
 public ResultSet rs=null,rs2=null,rs3=null,rs4=null;
 String rt_ans="",ex_opt="",aud_a="",aud_b="",aud_c="",aud_d="",ques="",cor_ans="";
 String ex_ad=null,mw="";
 public String q[]={"5000","10000","20000","40000","80000","160000","320000","640000","1250000","2500000","5000000","10000000","30000000","50000000","70000000"};
 String p[]={"0","10000","320000","10000000","50000000","70000000"};
 String qw[]={"5 Thousand","10 thousand","20 thousand","40 thousand","80 Thousand","1 lac 60 thousand","3 lac 20 thousand","6 lac 40 thousand","12 lac 50 thousand","25 lac","50 lac","1 crore","3 crore","5 crore","7 crore"};
 String pw[]={"none","10 thousand","3 lac 20 thousand","1 crore","5 crore","7 crore"}; 
 int qc=0,c=1,pad=0,flag=-1,dc=1;
    /**
     * Creates new form quiz
     */
    public quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cheque = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tcn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tcmw = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tcmn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        goodbye = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taq = new javax.swing.JTextArea();
        tcal = new javax.swing.JLabel();
        bca = new javax.swing.JButton();
        tgbm = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        cap = new javax.swing.JButton();
        l50 = new javax.swing.JButton();
        x2 = new javax.swing.JButton();
        ea = new javax.swing.JButton();
        cb = new javax.swing.JButton();
        cd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tq = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ca = new javax.swing.JButton();
        cc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tqp = new javax.swing.JLabel();
        bq = new javax.swing.JButton();
        p9 = new javax.swing.JButton();
        p10 = new javax.swing.JButton();
        p7 = new javax.swing.JButton();
        p1 = new javax.swing.JButton();
        p8 = new javax.swing.JButton();
        p13 = new javax.swing.JButton();
        p14 = new javax.swing.JButton();
        p11 = new javax.swing.JButton();
        p12 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        p15 = new javax.swing.JButton();
        p6 = new javax.swing.JButton();
        p3 = new javax.swing.JButton();
        p4 = new javax.swing.JButton();
        p5 = new javax.swing.JButton();

        cheque.setTitle("CHEQUE OF APPRECIATION");
        cheque.setMinimumSize(new java.awt.Dimension(750, 400));
        cheque.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                chequeWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                chequeWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("KAUN BANEGA CROREPATI");

        jLabel7.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        jLabel7.setText("Pay to");

        tcn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        jLabel9.setText("Money in words");

        tcmw.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        jLabel11.setText("Money (Rs.)");

        tcmn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Valid only in sunbeam bhagwanpur");

        jLabel16.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel16.setText("Amitabh Bachhan");

        jLabel15.setText("Signature");

        jLabel8.setFont(new java.awt.Font("Broadway", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 102));
        jLabel8.setText("CHEQUE OF APPRECIATION");

        jLabel10.setText("Developer");

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel12.setText("Shivam Agrawal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel10)
                                .addGap(324, 324, 324)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel7)))
                                .addGap(115, 115, 115)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcmw, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tcmn, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tcn, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel8)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(tcn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tcmw, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tcmn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout chequeLayout = new javax.swing.GroupLayout(cheque.getContentPane());
        cheque.getContentPane().setLayout(chequeLayout);
        chequeLayout.setHorizontalGroup(
            chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chequeLayout.setVerticalGroup(
            chequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cheque.getAccessibleContext().setAccessibleParent(this);

        goodbye.setTitle("GOOD BYE!!!!!!");
        goodbye.setMinimumSize(new java.awt.Dimension(700, 400));
        goodbye.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                goodbyeWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setMinimumSize(new java.awt.Dimension(601, 309));

        taq.setEditable(false);
        taq.setBackground(new java.awt.Color(255, 102, 102));
        taq.setColumns(20);
        taq.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        taq.setLineWrap(true);
        taq.setRows(5);
        taq.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taq);

        tcal.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        tcal.setText("Correct answer");

        bca.setBackground(new java.awt.Color(102, 255, 102));
        bca.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        bca.setMaximumSize(new java.awt.Dimension(45, 9));
        bca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaActionPerformed(evt);
            }
        });

        tgbm.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgbm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(tcal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bca, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(tgbm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout goodbyeLayout = new javax.swing.GroupLayout(goodbye.getContentPane());
        goodbye.getContentPane().setLayout(goodbyeLayout);
        goodbyeLayout.setHorizontalGroup(
            goodbyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        goodbyeLayout.setVerticalGroup(
            goodbyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KAUN BANEGA CROREPATI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "lifelines", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Handwriting", 0, 10), new java.awt.Color(255, 0, 0))); // NOI18N

        cap.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        cap.setForeground(new java.awt.Color(0, 153, 153));
        cap.setText("AUDIENCE POLL");
        cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capActionPerformed(evt);
            }
        });

        l50.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        l50.setForeground(new java.awt.Color(0, 153, 153));
        l50.setText("50:50");
        l50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l50ActionPerformed(evt);
            }
        });

        x2.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        x2.setForeground(new java.awt.Color(0, 153, 153));
        x2.setText("DOUBLE DIP (X2)");
        x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2ActionPerformed(evt);
            }
        });

        ea.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        ea.setForeground(new java.awt.Color(0, 153, 153));
        ea.setText("EXPERT ADVICE");
        ea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ea)
                .addContainerGap())
        );

        cb.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        cd.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });

        tq.setBackground(new java.awt.Color(255, 204, 102));
        tq.setColumns(20);
        tq.setFont(new java.awt.Font("Lucida Handwriting", 0, 13)); // NOI18N
        tq.setLineWrap(true);
        tq.setRows(5);
        tq.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tq);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel4.setText("B");

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel5.setText("D");

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel6.setText("Q");

        ca.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });

        cc.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel2.setText("A");

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel3.setText("C");

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        jLabel1.setText("THIS QUESTION FOR:");

        tqp.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N

        bq.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        bq.setForeground(new java.awt.Color(255, 0, 0));
        bq.setText("QUIT");
        bq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bqActionPerformed(evt);
            }
        });

        p9.setBackground(new java.awt.Color(153, 255, 153));
        p9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p9.setText("12,50,000");

        p10.setBackground(new java.awt.Color(153, 255, 153));
        p10.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p10.setText("25 LAC");

        p7.setBackground(new java.awt.Color(102, 255, 255));
        p7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p7.setForeground(new java.awt.Color(255, 0, 0));
        p7.setText("3,20,000");

        p1.setBackground(new java.awt.Color(153, 255, 153));
        p1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p1.setText("5,000");

        p8.setBackground(new java.awt.Color(153, 255, 153));
        p8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p8.setText("6,40,000");

        p13.setBackground(new java.awt.Color(153, 255, 153));
        p13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p13.setText("3 CRORE");

        p14.setBackground(new java.awt.Color(102, 255, 255));
        p14.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p14.setForeground(new java.awt.Color(255, 51, 51));
        p14.setText("5 CRORE");

        p11.setBackground(new java.awt.Color(153, 255, 153));
        p11.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p11.setText("50 LAC");

        p12.setBackground(new java.awt.Color(102, 255, 255));
        p12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p12.setForeground(new java.awt.Color(255, 0, 0));
        p12.setText("1 CRORE");

        p2.setBackground(new java.awt.Color(102, 255, 255));
        p2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 0, 51));
        p2.setText("10,000");

        p15.setBackground(new java.awt.Color(102, 255, 255));
        p15.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p15.setForeground(new java.awt.Color(255, 0, 0));
        p15.setText("7 crore");

        p6.setBackground(new java.awt.Color(153, 255, 153));
        p6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p6.setText("1,60,000");

        p3.setBackground(new java.awt.Color(153, 255, 153));
        p3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p3.setText("20,000");

        p4.setBackground(new java.awt.Color(153, 255, 153));
        p4.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p4.setText("40,000");

        p5.setBackground(new java.awt.Color(153, 255, 153));
        p5.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        p5.setText("80,000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75)
                                .addComponent(tqp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 114, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(bq, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(ca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(cc, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(29, 29, 29)
                                .addComponent(cd, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(cb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(bq)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tqp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(p15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 p1.setEnabled(false);
          p2.setEnabled(false);
           p3.setEnabled(false);
            p4.setEnabled(false);
             p5.setEnabled(false);
              p6.setEnabled(false);
               p7.setEnabled(false);
                p8.setEnabled(false);
                 p9.setEnabled(false);
                  p10.setEnabled(false);
                   p11.setEnabled(false);
                    p12.setEnabled(false);
                     p13.setEnabled(false);
                      p14.setEnabled(false);
                       p15.setEnabled(false);
        question();        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
         int res= JOptionPane.showConfirmDialog(rootPane, "Lock kar diya jae?");
       if(res==JOptionPane.YES_OPTION)
       {
        if (rt_ans.equalsIgnoreCase("a"))
        { 
            JOptionPane.showMessageDialog(rootPane, "Correct Answer");
            if (qc<q.length)
            {   
                qc++;
                if (qc==2 || qc==7 || qc==12 || qc==14 || qc==15)
                {
                    pad++;
                    cheque.setVisible(true);
                }
               
                question();
                
            }
        }
        else
        { if(dc!=2)
        { tgbm.setText("wrong Answer ....BETTER LUCK NEXT TIME...YOU WON Rs. "+p[pad]);
            leave();
            dispose();
        }
        else
        {
            dc=1;
            ca.setEnabled(false);
        }
        }
       }
    }//GEN-LAST:event_caActionPerformed
    
    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
        int res= JOptionPane.showConfirmDialog(rootPane, "Lock kar diya jae?");
       if(res==JOptionPane.YES_OPTION)
       {
        if (rt_ans.equalsIgnoreCase("b"))
           { 
            JOptionPane.showMessageDialog(rootPane, "Correct Answer");
            if (qc<q.length)
            {   
                qc++;
                if (qc==2 || qc==7 || qc==12 ||qc==14 || qc==15)
                {
                    pad++;
                    cheque.setVisible(true);
                }
                question();
            }
        }
        else
        {
          if(dc!=2)
        { tgbm.setText("wrong Answer ....BETTER LUCK NEXT TIME...YOU WON Rs. "+p[pad]);
            leave();
            dispose();
        }
        else
        {
            dc=1;
             cb.setEnabled(false);
        }
          }
       }
    }//GEN-LAST:event_cbActionPerformed

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        // TODO add your handling code here:
        int res= JOptionPane.showConfirmDialog(rootPane, "Lock kar diya jae?");
       if(res==JOptionPane.YES_OPTION)
       {
       if (rt_ans.equalsIgnoreCase("c"))
           { 
            JOptionPane.showMessageDialog(rootPane, "Correct Answer");
            if (qc<q.length )
            {   
                qc++;
                if (qc==2 || qc==7 || qc==12 || qc==14 || qc==15)
                {
                    pad++;
                    cheque.setVisible(true);
                }
                question();
            }
        }
        else
       {
           if(dc!=2)
        { tgbm.setText("wrong Answer ....BETTER LUCK NEXT TIME...YOU WON Rs. "+p[pad]);
            leave();
            dispose();
        }
        else
        {
            dc=1;
             cc.setEnabled(false);
        }  
       }
       }
    }//GEN-LAST:event_ccActionPerformed

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed
        // TODO add your handling code here:
        int res= JOptionPane.showConfirmDialog(rootPane, "Lock kar diya jae?");
       if(res==JOptionPane.YES_OPTION)
       {
        if (rt_ans.equalsIgnoreCase("d"))
           { 
            JOptionPane.showMessageDialog(rootPane, "Correct Answer");
            if (qc<q.length)
            {   
                qc++;
                if (qc==2 || qc==7 || qc==12 ||qc==14 || qc==15)
                {
                    pad++;
                    cheque.setVisible(true);
                }
                question();
            }
        }
        else
        {  
         if(dc!=2)
        { tgbm.setText("wrong Answer ....BETTER LUCK NEXT TIME...YOU WON Rs. "+p[pad]);
            leave();
            dispose();
        }
        else
        {
            dc=1;
             cd.setEnabled(false);
        }
           
        }
       }
    }//GEN-LAST:event_cdActionPerformed

    private void capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"A : \t"+ aud_a+"\n B : \t"+ aud_b+"\n C : \t"+ aud_c+"\n D : \t"+aud_d );
        cap.setEnabled(false);
    }//GEN-LAST:event_capActionPerformed

    private void l50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l50ActionPerformed
        // TODO add your handling code here:
         bq.setEnabled(false);
          JOptionPane.showMessageDialog(rootPane,"Now You cannot Quit For This Partiular Question!! You Have to Answer");
        x2.setVisible(false);
        
        if (!(rt_ans.equalsIgnoreCase("a") || ex_opt.equalsIgnoreCase("a")))
            ca.setVisible(false);
         if (!(rt_ans.equalsIgnoreCase("b") || ex_opt.equalsIgnoreCase("b")))
            cb.setVisible(false);
         if (!(rt_ans.equalsIgnoreCase("c") || ex_opt.equalsIgnoreCase("c")))
            cc.setVisible(false);
         if (!(rt_ans.equalsIgnoreCase("d") || ex_opt.equalsIgnoreCase("d")))
            cd.setVisible(false);
         l50.setEnabled(false);
    }//GEN-LAST:event_l50ActionPerformed

    private void eaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, ex_ad);
        ea.setEnabled(false);
    }//GEN-LAST:event_eaActionPerformed

    private void x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2ActionPerformed
        // TODO add your handling code here:
        bq.setEnabled(false);
          JOptionPane.showMessageDialog(rootPane,"Now You cannot Quit For This Partiular Question!! You Have to Answer");
        l50.setVisible(false);
        x2.setEnabled(false);
        dc=2;
        
    }//GEN-LAST:event_x2ActionPerformed

    private void bqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bqActionPerformed
        // TODO add your handling code here:
         int res= JOptionPane.showConfirmDialog(rootPane, "Are you sure U wanna 'Quit'?");
       if(res==JOptionPane.YES_OPTION)
       {
        tgbm.setText("Its OK!! there is nothing wrong in quitting....");
        flag=0;
        
        leave();
       }
    }//GEN-LAST:event_bqActionPerformed

    private void chequeWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_chequeWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chequeWindowOpened

    private void chequeWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_chequeWindowActivated
        // TODO add your handling code here:
        try
        {  Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shivam","root","shivam");
            stmt=con.createStatement();
            String query="Select name from curpl;";
            rs=stmt.executeQuery(query);
            int rs1=0;
            if(rs.next())
            {
                String name=rs.getString("name");
                 tcn.setText(name);
                 String query1="",miw="";
                 if(flag==-1)
                 {
                    mw=p[pad];
                    miw=pw[pad];
                    query1="UPDATE CURPL SET wamt='"+mw+"';";
                    rs1=stmt.executeUpdate(query1);
                 }
                 else if(flag==0)
                 {   mw=q[qc-1];
                    miw=qw[qc-1];
                    query1="UPDATE CURPL SET wamt='"+mw+"';";
                    rs1=stmt.executeUpdate(query1);
                 }
                 tcmn.setText(mw+"");
                 tcmw.setText(miw+"");
            }
        }
          catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_chequeWindowActivated

    private void bcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcaActionPerformed

    private void goodbyeWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_goodbyeWindowOpened
        // TODO add your handling code here:
        if(qc!=15)
        {
         taq.setText(ques);
            bca.setText(cor_ans);
        }
    }//GEN-LAST:event_goodbyeWindowOpened

    /**
     * @param args the command line arguments
     */
    
    void question()
    {   
         if(qc>=15)
    p15.setEnabled(true);
if(qc>=14)
    p14.setEnabled(true);
if(qc>=13)
    p13.setEnabled(true);
if(qc>=12)
    p12.setEnabled(true);
if(qc>=11)
    p11.setEnabled(true);
if(qc>=10)
    p10.setEnabled(true);
if(qc>=9)
    p9.setEnabled(true);
if(qc>=8)
    p8.setEnabled(true);
if(qc>=7)
    p7.setEnabled(true);
if(qc>=6)
    p6.setEnabled(true);
if(qc>=5)
    p5.setEnabled(true);
if(qc>=4)
    p4.setEnabled(true);
if(qc>=3)
    p3.setEnabled(true);
if(qc>=2)
    p2.setEnabled(true);
if(qc>=1)
    p1.setEnabled(true);
        try
        {  if(qc==15)
        {
            tgbm.setText("Congrats!!! you are a champ!! impeccable performance");
            taq.append("you have completed the game\n");
            tcal.setVisible(false);
            bca.setVisible(false);
            int lc=0;
            if(cap.isEnabled())
                lc++;
            if(l50.isEnabled())
                lc++;
            if(x2.isEnabled())
                lc++;
            if(ea.isEnabled())
                lc++;
            taq.append("no. of lifelines left:\t"+lc);
            leave();
           this.dispose();
           
        }
        else
        {
            dc=1;
            tq.setEditable(false);
             ca.setEnabled(true);
             bq.setEnabled(true);
            cb.setEnabled(true);
            cc.setEnabled(true);
            cd.setEnabled(true);
            ca.setVisible(true);
            cb.setVisible(true);
            cc.setVisible(true);
            cd.setVisible(true);
            x2.setVisible(true);
            l50.setVisible(true);
            tqp.setText(""+qw[qc]);
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shivam","root","shivam");
            stmt=con.createStatement();
            String query10="Select max(qno) from q"+q[qc]+" ;";
            rs4=stmt.executeQuery(query10);
            int max=0;
            if(rs4.next())
                max=rs4.getInt("max(qno)");
            int no=1+(int) (Math.random()*max);
            
            String query1="Select * from q"+q[qc]+" where qno=";
            rs=stmt.executeQuery(query1+no);
            if(rs.next())
            {
                 ques=rs.getString("ques");
                String o_a=rs.getString("opt_a");
                String o_b=rs.getString("opt_b");
                String o_c=rs.getString("opt_c");
                String o_d=rs.getString("opt_d");
                rt_ans=rs.getString("rt_opt");
                cor_ans=rs.getString("opt_"+rt_ans);
                ex_opt=rs.getString("ex_opt50");
                aud_a=rs.getString("aud_a");
                aud_b=rs.getString("aud_b");
                aud_c=rs.getString("aud_c");
                aud_d=rs.getString("aud_d");
                ex_ad=rs.getString("ex_ad");
                tq.setText(ques);
                ca.setText(o_a);
                cb.setText(o_b);
                cc.setText(o_c);
                cd.setText(o_d);
            }
        }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    void leave()
    {   
          dispose();        
       goodbye.setVisible(true);
       cheque.setVisible(true);
        chequeWindowActivated(null);
                  
        try
        {  Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shivam","root","shivam");
            stmt=con.createStatement();
           int f=-1;String n="",a="",mn="",gen="";
          long woamt=0,pwamt=0;
           
            String query3="Select * from curpl where sno=1;";
            rs2=stmt.executeQuery(query3);
            if(rs2.next())
            {   
              
                n=rs2.getString("name");
                a=rs2.getString("age");
                mn=rs2.getString("mno");
                 gen=rs2.getString("gender");
                  woamt=Long.parseLong(rs2.getString("wamt"));
                 
                  
            }
          String query4="Select mno,wamt from highsc;";
            rs3=stmt.executeQuery(query4);
            
            while(rs3.next())
            {  
                if(mn.equals(rs3.getString("mno")))
                {
                    f=0;
                    if(f==0)
                        pwamt=Long.parseLong(rs3.getString("wamt"));
                    break;
                }
            }
            if(f==-1)
            {  
               String query5="Insert into highsc values('"+n+"',"+a+",'"+gen+"',"+mn+","+woamt+");";
            int rs4=stmt.executeUpdate(query5); 
            }
            else
            { 
                if(woamt>pwamt)
            {String query5="update highsc set wamt="+woamt+",age="+a+" where mno="+mn+";";
               int rs4=stmt.executeUpdate(query5); 
            }
            }   
            String query7="delete from curpl;";
             int rs5=stmt.executeUpdate(query7);
          }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
         
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
           

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bca;
    private javax.swing.JButton bq;
    private javax.swing.JButton ca;
    private javax.swing.JButton cap;
    private javax.swing.JButton cb;
    private javax.swing.JButton cc;
    private javax.swing.JButton cd;
    private javax.swing.JFrame cheque;
    private javax.swing.JButton ea;
    private javax.swing.JFrame goodbye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton l50;
    private javax.swing.JButton p1;
    private javax.swing.JButton p10;
    private javax.swing.JButton p11;
    private javax.swing.JButton p12;
    private javax.swing.JButton p13;
    private javax.swing.JButton p14;
    private javax.swing.JButton p15;
    private javax.swing.JButton p2;
    private javax.swing.JButton p3;
    private javax.swing.JButton p4;
    private javax.swing.JButton p5;
    private javax.swing.JButton p6;
    private javax.swing.JButton p7;
    private javax.swing.JButton p8;
    private javax.swing.JButton p9;
    private javax.swing.JTextArea taq;
    private javax.swing.JLabel tcal;
    private javax.swing.JLabel tcmn;
    private javax.swing.JLabel tcmw;
    private javax.swing.JLabel tcn;
    private javax.swing.JLabel tgbm;
    private javax.swing.JTextArea tq;
    private javax.swing.JLabel tqp;
    private javax.swing.JButton x2;
    // End of variables declaration//GEN-END:variables

    private void chequeWindowActivated() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
